console:
  bot:  bot
  prompt: ">>>"
  license_keys: $BOT_ROOT/config/license.keys
  scheduler:
    name: Scheduler1
    debug_level: 0
    add_listeners: False
    remove_all_jobs: False

voice:
  license_keys: $BOT_ROOT/config/license.keys
  tts: osx
  stt: azhang
  osx:
    classname: talky.clients.voice.tts.osxsay.OSXSayTextToSpeach
  pytts:
    classname: talky.clients.voice.tts.pyttssay.PyTTSSayTextToSpeach
    rate_adjust: 50
  azhang:
    classname: talky.clients.voice.stt.azhang.AnthonyZhangSpeechToText
    ambient_adjust: 3
    service: ibm

rest:
  host: 0.0.0.0
  port: 8989
  debug: false
  workers: 4
  license_keys: $BOT_ROOT/config/license.keys

webchat:
  host: 0.0.0.0
  port: 8090
  debug: false
  license_keys: $BOT_ROOT/config/license.keys
  api: /api/web/v1.0/ask

twitter:
  polling: true
  polling_interval: 49
  streaming: false
  use_status: true
  use_direct_message: true
  auto_follow: true
  storage: file
  storage_location: $BOT_ROOT/storage/twitter.data
  welcome_message: Thanks for following me, send me a message and I'll try and help
  license_keys: $BOT_ROOT/config/license.keys

xmpp:
  server: talk.google.com
  port: 5222
  xep_0030: true
  xep_0004: true
  xep_0060: true
  xep_0199: true
  license_keys: $BOT_ROOT/config/license.keys

socket:
  host: 127.0.0.1
  port: 9999
  queue: 5
  debug: true
  license_keys: $BOT_ROOT/config/license.keys

telegram:
  unknown_command: Sorry, that is not a command I have been taught yet!
  license_keys: $BOT_ROOT/config/license.keys

facebook:
  host: 127.0.0.1
  port: 5000
  debug: false
  license_keys: $BOT_ROOT/config/license.keys

twilio:
  host: 127.0.0.1
  port: 5000
  debug: false
  license_keys: $BOT_ROOT/config/license.keys

slack:
  polling_interval: 1
  license_keys: $BOT_ROOT/config/license.keys

viber:
  name: Servusai
  avatar: http://viber.com/avatar.jpg
  license_keys: $BOT_ROOT/config/license.keys

line:
  host: 127.0.0.1
  port: 8084
  debug: false
  license_keys: $BOT_ROOT/config/license.keys

kik:
  bot_name: servusai
  webhook: https://93638f7a.ngrok.io/api/kik/v1.0/ask
  host: 127.0.0.1
  port: 8082
  debug: false
  license_keys: $BOT_ROOT/config/license.keys

#####################################################################################################
#

bot:
    brain: brain

    initial_question: Hi, how can I help you today?
    initial_question_srai: YINITIALQUESTION
    default_response: Sorry, I don't have an answer for that!
    default_response_srai: YEMPTY
    empty_string: YEMPTY
    exit_response: So long, and thanks for the fish!
    exit_response_srai: YEXITRESPONSE

    override_properties: true

    max_question_recursion: 1000
    max_question_timeout: 60
    max_search_depth: 100
    max_search_timeout: 60

    spelling:
      classname: programy.spelling.norvig.NorvigSpellingChecker
      corpus: $BOT_ROOT/spelling/corpus.txt
      check_before: false
      check_and_retry: false

    conversations:
      type: file
      config_name: file_storage
      #type: redis
      #config_name: redis_storage
      empty_on_start: true

    file_storage:
      dir: $BOT_ROOT/conversations

    redis_storage:
      host: localhost
      port: 6379

#####################################################################################################
#

brain:

    # Overrides
    overrides:
      allow_system_aiml: true
      allow_learn_aiml: true
      allow_learnf_aiml: true

    # Defaults
    defaults:
      default-get: unknown
      default-property: unknown
      default-map: unknown
      learn-filename: $BOT_ROOT/aiml/y-bot-learnf.aiml

    # Nodes
    nodes:
      pattern_nodes: $BOT_ROOT/config/pattern_nodes.conf
      template_nodes: $BOT_ROOT/config/template_nodes.conf

    # Binary
    binaries:
      save_binary: false
      load_binary: false
      binary_filename: /tmp/y-bot.brain
      load_aiml_on_binary_fail: false

    # Braintree
    braintree:
      file: /tmp/braintree.xml
      content: xml

    files:
        aiml:
            files: $BOT_ROOT/aiml
            extension: .aiml
            directories: true
            errors:
              file: /tmp/y-bot_errors.csv
              format: csv
              encoding: utf-8
              delete_on_start: true
            duplicates:
              file: /tmp/y-bot_duplicates.csv
              format: csv
              encoding: utf-8
              delete_on_start: true
            conversation:
              file: /tmp/y-bot-conversation.csv
              format: csv
              delete_on_start: true
        sets:
            files: $BOT_ROOT/sets
            extension: .txt
            directories: false
        maps:
            files: $BOT_ROOT/maps
            extension: .txt
            directories: false
        denormal: $BOT_ROOT/config/denormal.txt
        normal: $BOT_ROOT/config/normal.txt
        gender: $BOT_ROOT/config/gender.txt
        person: $BOT_ROOT/config/person.txt
        person2: $BOT_ROOT/config/person2.txt
        properties: $BOT_ROOT/config/properties.txt
        rdf:
            files:  $BOT_ROOT/rdf
            extension: .txt
            directories: true
        preprocessors: $BOT_ROOT/config/preprocessors.conf
        postprocessors: $BOT_ROOT/config/postprocessors.conf
        regex_templates: $BOT_ROOT/config/regex-templates.txt
        variables: $BOT_ROOT/config/default-variables.txt

    services:
        REST:
            classname: programy.services.rest.GenericRESTService
            method: GET
            host: 0.0.0.0
        Pannous:
            classname: programy.services.pannous.PannousService
            url: http://weannie.pannous.com/api
        Pandora:
            classname: programy.services.pandora.PandoraService
            url: http://www.pandorabots.com/pandora/talk-xml
        Wikipedia:
            classname: programy.services.wikipediaservice.WikipediaService
        DuckDuckGo:
            classname: programy.services.duckduckgo.DuckDuckGoService
            url: http://api.duckduckgo.com

    security:
        authentication:
            classname: programy.security.authenticate.passthrough.BasicPassThroughAuthenticationService
            denied_srai: AUTHENTICATION_FAILED
        authorisation:
            classname: programy.security.authorise.usergroupsauthorisor.BasicUserGroupAuthorisationService
            denied_srai: AUTHORISATION_FAILED
            usergroups: $BOT_ROOT/config/roles.yaml

    oob:
      default:
        classname: programy.oob.default.DefaultOutOfBandProcessor
      alarm:
        classname: programy.oob.alarm.AlarmOutOfBandProcessor
      camera:
        classname: programy.oob.camera.CameraOutOfBandProcessor
      clear:
        classname: programy.oob.clear.ClearOutOfBandProcessor
      dial:
        classname: programy.oob.dial.DialOutOfBandProcessor
      dialog:
        classname: programy.oob.dialog.DialogOutOfBandProcessor
      email:
        classname: programy.oob.email.EmailOutOfBandProcessor
      geomap:
        classname: programy.oob.map.MapOutOfBandProcessor
      schedule:
        classname: programy.oob.schedule.ScheduleOutOfBandProcessor
      search:
        classname: programy.oob.search.SearchOutOfBandProcessor
      sms:
        classname: programy.oob.sms.SMSOutOfBandProcessor
      url:
        classname: programy.oob.url.URLOutOfBandProcessor
      wifi:
        classname: programy.oob.wifi.WifiOutOfBandProcessor

    dynamic:
        variables:
            gettime: programy.dynamic.variables.datetime.GetTime
        sets:
            numeric: programy.dynamic.sets.numeric.IsNumeric
            roman:   programy.dynamic.sets.roman.IsRomanNumeral
        maps:
            romantodec: programy.dynamic.maps.roman.MapRomanToDecimal
            dectoroman: programy.dynamic.maps.roman.MapDecimalToRoman

